apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: run-review
  namespace: run-review
  labels:
    app.kubernetes.io/name: run-review
    app.kubernetes.io/component: app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: run-review.192.168.10.189.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: run-review
                port:
                  number: 3000
  tls:
    - hosts:
        - run-review.192.168.10.189.nip.io
      secretName: wildcard-cert
